language: node_js

node_js:
  - 0.10
  - 0.11

before_install:
  # required libs for android build tools
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar -zxf android-sdk_r22.6.2-linux.tgz -C $HOME
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --filter tool,platform-tool,android-19,sysimg-19,build-tools-19.0.3
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - npm install -g gulp
  - npm install -g cordova
  - cordova platform add android

script:
  - gulp build
