language: node_js

node_js:
  - 0.10
  - 0.11

before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz | tar -x -z -C $HOME
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --force --filter platform-tool,android-19,sysimg-19,build-tools-19.0.3
  - npm install -g gulp
  - npm install -g cordova
  - cordova platform add android

script:
  - gulp build
